# Generated by Django 4.2.6 on 2023-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
