# Generated by Django 4.2.6 on 2023-12-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu_site', '0003_location_alter_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mu_site.location'),
        ),
    ]
