# Generated by Django 4.2.6 on 2023-12-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu_site', '0006_organizer_meetup_date_alter_meetup_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='organizer',
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mu_site.organizer'),
        ),
    ]
