# Generated by Django 4.2.6 on 2023-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu_site', '0007_remove_meetup_organizer_meetup_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
    ]
